!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acquisition_mode: Continuous
  acquisition_rate: 12.0
  balance_ratio_abs: 1.8
  balance_ratio_selector: Red
  binning_x: 1
  binning_y: 1
  decimation_x: 1
  decimation_y: 1
  exposure: 1000.0
  exposure_auto: 'Off'
  exposure_auto_alg: Mean
  exposure_auto_max: 500000
  exposure_auto_min: 140
  exposure_auto_outliers: 0
  exposure_auto_rate: 100
  exposure_auto_target: 50
  exposure_auto_tol: 5
  frame_id: image_raw
  gain: 10.0
  gain_auto: 'Off'
  gain_auto_max: 22.0
  gain_auto_min: 0.0
  gain_auto_outliers: 0
  gain_auto_rate: 100
  gain_auto_target: 50
  gain_auto_tol: 5
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acquisition_mode: Continuous
      acquisition_rate: 12.0
      balance_ratio_abs: 1.8
      balance_ratio_selector: Red
      binning_x: 1
      binning_y: 1
      decimation_x: 1
      decimation_y: 1
      exposure: 1000.0
      exposure_auto: 'Off'
      exposure_auto_alg: Mean
      exposure_auto_max: 500000
      exposure_auto_min: 140
      exposure_auto_outliers: 0
      exposure_auto_rate: 100
      exposure_auto_target: 50
      exposure_auto_tol: 5
      frame_id: image_raw
      gain: 10.0
      gain_auto: 'Off'
      gain_auto_max: 22.0
      gain_auto_min: 0.0
      gain_auto_outliers: 0
      gain_auto_rate: 100
      gain_auto_target: 50
      gain_auto_tol: 5
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      height: 2672
      id: 0
      iris_auto_target: 50
      iris_mode: 'Off'
      iris_video_level_max: 0
      iris_video_level_min: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pixel_format: BayerGR12
      ptp_mode: 'Off'
      roi_height: 0
      roi_offset_x: 0
      roi_offset_y: 0
      roi_width: 0
      state: true
      stream_bytes_per_second: 20000000
      sync_in_selector: SyncIn1
      sync_out_polarity: Normal
      sync_out_selector: SyncOut2
      sync_out_source: Exposing
      trig_timestamp_topic: ''
      trigger_activation: RisingEdge
      trigger_delay: 0.0
      trigger_mode: 'On'
      trigger_selector: FrameStart
      trigger_source: FixedRate
      type: ''
      whitebalance_auto: 'Off'
      whitebalance_auto_rate: 100
      whitebalance_auto_tol: 5
      width: 4008
    state: []
  height: 2672
  iris_auto_target: 50
  iris_mode: 'Off'
  iris_video_level_max: 0
  iris_video_level_min: 0
  pixel_format: BayerGR12
  ptp_mode: 'Off'
  roi_height: 0
  roi_offset_x: 0
  roi_offset_y: 0
  roi_width: 0
  stream_bytes_per_second: 20000000
  sync_in_selector: SyncIn1
  sync_out_polarity: Normal
  sync_out_selector: SyncOut2
  sync_out_source: Exposing
  trig_timestamp_topic: ''
  trigger_activation: RisingEdge
  trigger_delay: 0.0
  trigger_mode: 'On'
  trigger_selector: FrameStart
  trigger_source: FixedRate
  whitebalance_auto: 'Off'
  whitebalance_auto_rate: 100
  whitebalance_auto_tol: 5
  width: 4008
state: []